
export const LATESTMOVIES_REQUEST = "LATESTMOVIES_REQUEST";
export const LATESTMOVIES_SUCCESS = "LATESTMOVIES_SUCCESS";
export const LATESTMOVIES_FAILURE = "LATESTMOVIES_FAILURE";

export const MOVIES_SUCCESS = "MOVIES_SUCCESS";

export const INC ="INC";
export const DEC = "DEC";


export const SEARCH_JOB_REQUEST="SEARCH_JOB_REQUEST";
export const SEARCH_JOB_SUCCESS="SEARCH_JOB_SUCCESS";
export const SEARCH_JOB_FAILURE="SEARCH_JOB_REQUEST";

export const SEARCHTEXT="SEARCHTEXT";